k8_kubelet_extra_args: "--fail-swap-on=false --cgroup-driver=cgroupfs --node-ip={{ node_ip }}"
k8_pod_network_cidr: '10.0.1.0/16'
k8_apiserver_advertise_address: ''
k8_ignore_preflight_errors: 'all'
# Flannel config files.
k8_flannel_manifest_file_rbac: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml
k8_flannel_manifest_file: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
k8_enable_web_ui: True
